### Create pdfs
POST http://localhost:3000/create?height=480&width=480
Content-Type: application/json

{
  "content": "<table><tr><th>Company</th><th>Contact</th><th>Country</th></tr><tr><td>Alfreds Futterkiste</td><td>Maria Anders</td><td>Germany</td></tr><tr><td>Centro comercial Moctezuma</td><td>Francisco Chang</td><td>Mexico</td></tr></table>"
}


###
POST http://localhost:3000/generateapi
Content-Type: application/json

{
  "key": "f0104ed7-4312-4248-8aac-54e3fdd7d664"
}

###
GET http://localhost:3000/all

### 
GET http://localhost:3000/download
Content-Type: application/json

{
  "id":"5"
}

### 
GET http://localhost:3000/delete
Content-Type: application/json

{
  "id":"7"
}